trigger:
- production

pool:
  name: 'Azure'
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  displayName: 'Download env'
  inputs:
    secureFile: .env

- task: CopyFiles@2
  displayName: 'Copy .env to source code'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: .env
    TargetFolder: '$(Build.SourcesDirectory)'
    
- script: |
    echo "Zip all files"
    zip -r release.zip . -x "*.git*"
  displayName: 'Zip files to upload server'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'release.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
