trigger:
- production

pool:
  name: 'Azure'
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    architecture: 'x64'

- task: DownloadSecureFile@1
  inputs:
    secureFile: '.env'
  displayName: 'Download .env file'
  
- task: CopyFiles@2
  displayName: 'Copy .env to source code'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: .env
    TargetFolder: '$(Build.SourcesDirectory)'
    
- script: |
    python -m venv venv
    source venv/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    cd myproject
    python manage.py collectstatic --noinput
  displayName: 'Install prerequisites and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'myproject/staticfiles/**'
    ArtifactName: 'drop'
    publishLocation: 'Container'
